Date::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Date::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Date::DATE_FORMATS[:date] = '%Y/%m/%d'
Date::DATE_FORMATS[:time] = '%H:%M:%S'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'